# Generated by Django 5.2.6 on 2026-04-16 17:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('publishable_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('allowed_origins', models.JSONField(blank=True, default=list, help_text='List of allowed browser origins, e.g. ["https://mysite.tilda.ws"].')),
                ('platform_preset', models.CharField(choices=[('tilda', 'Tilda'), ('generic', 'Generic')], db_index=True, default='tilda', max_length=32)),
                ('widget_enabled', models.BooleanField(db_index=True, default=True)),
                ('webhook_enabled', models.BooleanField(default=True, help_text='Reserved for future per-site webhook toggles; MVP order webhook is global.')),
                ('config_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_sites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralLeadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lead_submitted', 'Lead submitted')], db_index=True, default='lead_submitted', max_length=32)),
                ('ref_code', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('customer_email', models.CharField(blank=True, default='', max_length=254)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=64)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('page_url', models.TextField(blank=True, default='')),
                ('form_id', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_events', to='referrals.partnerprofile')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_events', to='referrals.site')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
