# Generated by Django 5.2.6 on 2026-04-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0005_referralleadevent_client_observed_outcome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralleadevent',
            name='client_observed_outcome',
            field=models.CharField(blank=True, choices=[('', 'Not reported'), ('success_observed', 'Client observed success (not a confirmed conversion)'), ('failure_observed', 'Client observed failure (heuristic)'), ('not_observed', 'No confirmation / inconclusive (not a failure)')], db_index=True, default='', help_text='Optional client-side observation (heuristic; not a confirmed conversion).', max_length=32),
        ),
        migrations.AlterField(
            model_name='referralleadevent',
            name='client_outcome_reason',
            field=models.CharField(blank=True, default='', help_text='Short opaque reason from the client (no PII).', max_length=255),
        ),
        migrations.AlterField(
            model_name='referralleadevent',
            name='client_outcome_source',
            field=models.CharField(blank=True, default='', help_text='Origin of client_observed_outcome (e.g. tilda_dom_heuristic).', max_length=64),
        ),
        migrations.CreateModel(
            name='PublicLeadIngestAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_name', models.CharField(blank=True, db_index=True, default='', help_text='Wire event: lead_submitted, lead_client_outcome, or empty.', max_length=32)),
                ('public_code', models.CharField(db_index=True, help_text='Stable code from public response (same as client-visible code).', max_length=64)),
                ('internal_reason', models.CharField(blank=True, default='', help_text='Operator-only reason when public body is masked.', max_length=64)),
                ('http_status', models.PositiveSmallIntegerField(db_index=True)),
                ('origin_present', models.BooleanField(default=False)),
                ('origin_header_prefix', models.CharField(blank=True, default='', max_length=256)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('form_id', models.CharField(blank=True, default='', max_length=255)),
                ('page_key', models.CharField(blank=True, default='', max_length=512)),
                ('submission_stage_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('client_observed_outcome_snapshot', models.CharField(blank=True, default='', max_length=32)),
                ('throttle_scope', models.CharField(blank=True, default='', max_length=16)),
                ('has_email', models.BooleanField(default=False)),
                ('has_phone', models.BooleanField(default=False)),
                ('lead_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_ingest_audits', to='referrals.referralleadevent')),
                ('site', models.ForeignKey(blank=True, help_text='Null when site UUID in query did not resolve.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_ingest_audits', to='referrals.site')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['site', '-created_at'], name='referrals_p_site_id_83dcaa_idx'), models.Index(fields=['site', 'public_code', '-created_at'], name='referrals_p_site_id_67749b_idx')],
            },
        ),
    ]
