# Generated by Django 5.2.6 on 2026-05-01 02:02

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0014_siteowneractivitylog_owner_nullable_site'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyChallengeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('completed', 'Completed')], db_index=True, default='started', max_length=16)),
                ('score', models.PositiveIntegerField(default=0)),
                ('base_xp', models.PositiveIntegerField(default=0)),
                ('multiplier', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=7)),
                ('awarded_xp', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-challenge_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GamificationProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_total', models.PositiveIntegerField(default=0)),
                ('streak_days', models.PositiveIntegerField(default=0)),
                ('last_activity_date', models.DateField(blank=True, null=True)),
                ('best_challenge_score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='XPEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('daily_challenge', 'Daily challenge'), ('link_click', 'Link click'), ('lead_created', 'Lead created'), ('lead_confirmed', 'Lead confirmed'), ('purchase_confirmed', 'Purchase confirmed'), ('manual', 'Manual')], db_index=True, max_length=32)),
                ('amount', models.PositiveIntegerField()),
                ('base_amount', models.PositiveIntegerField(default=0)),
                ('multiplier', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=7)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailychallengeattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_challenge_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamification_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='xpevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dailychallengeattempt',
            constraint=models.UniqueConstraint(fields=('user', 'challenge_date'), name='uniq_daily_challenge_attempt_user_date'),
        ),
        migrations.AddIndex(
            model_name='xpevent',
            index=models.Index(fields=['user', '-created_at'], name='referrals_x_user_id_25cde8_idx'),
        ),
    ]
