# Generated by Django 5.2.6 on 2026-05-03 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0017_gamification_challenge_lives'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('xp_awarded', models.PositiveIntegerField(default=0)),
                ('progress_current', models.PositiveIntegerField(default=0)),
                ('progress_target', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user_achievements',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.AlterField(
            model_name='xpevent',
            name='source',
            field=models.CharField(
                choices=[
                    ('daily_challenge', 'Daily challenge'),
                    ('link_click', 'Link click'),
                    ('lead_created', 'Lead created'),
                    ('lead_confirmed', 'Lead confirmed'),
                    ('purchase_confirmed', 'Purchase confirmed'),
                    ('achievement', 'Achievement'),
                    ('manual', 'Manual'),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name='userachievement',
            index=models.Index(fields=['user', 'code'], name='referrals_u_user_id_9699fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='userachievement',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='uniq_user_achievement_code'),
        ),
        migrations.RenameIndex(
            model_name='sitemembership',
            new_name='referrals_s_site_id_131551_idx',
            old_name='referrals_s_site_id_0f98fd_idx',
        ),
        migrations.RenameIndex(
            model_name='sitemembership',
            new_name='referrals_s_user_id_b54ab7_idx',
            old_name='referrals_s_user_id_09f0a2_idx',
        ),
    ]
