# Generated by Django 5.2.6 on 2026-05-04 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0022_gamificationprofile_fast_life_regen_until'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralShopOwnedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(db_index=True, max_length=64)),
                ('item_type', models.CharField(db_index=True, max_length=32)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-acquired_at'],
            },
        ),
        migrations.AddField(
            model_name='gamificationprofile',
            name='active_minigame_frame',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='referralshopowneditem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_shop_owned_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='referralshopowneditem',
            constraint=models.UniqueConstraint(fields=('user', 'item_code'), name='referrals_shop_owned_user_item_uq'),
        ),
    ]
