# Generated by Django 5.2.6 on 2026-05-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0023_shop_owned_frame_and_active_minigame_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramBudgetTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='RUB', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=16)),
                ('payment_method', models.CharField(choices=[('bank_card', 'Bank card')], default='bank_card', max_length=32)),
                ('provider', models.CharField(blank=True, choices=[('tbank', 'T-Bank')], max_length=32, null=True)),
                ('provider_payment_id', models.CharField(blank=True, max_length=128, null=True)),
                ('provider_order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='programbudgettopup',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_budget_topups', to='referrals.partnerprofile'),
        ),
        migrations.AddIndex(
            model_name='programbudgettopup',
            index=models.Index(fields=['partner', 'status', '-created_at'], name='referrals_p_partner_6c5920_idx'),
        ),
    ]
