# Generated by Django 5.2.6 on 2026-05-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0025_site_archived_at_order_site'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referralpointtransaction',
            new_name='referrals_r_user_id_5c15b4_idx',
            old_name='referrals_r_user_id_df7188_idx',
        ),
    ]
