from django.urls import path

from .views import (
    PartnerDashboardView,
    PartnerOnboardView,
    ProjectOwnerCreateView,
    ProjectOwnerDetailView,
    ProjectSiteOwnerCreateView,
    ReferralCaptureView,
    SiteOwnerCreateView,
    SiteOwnerIntegrationActivateView,
    SiteOwnerBootstrapView,
    SiteOwnerIntegrationAnalyticsView,
    SiteOwnerIntegrationDiagnosticsView,
    SiteOwnerIntegrationView,
    SiteOwnerIntegrationVerifyView,
    SiteOwnerReachabilityView,
    SiteOwnerSiteMembersListView,
    SiteOwnerSitesListView,
)

urlpatterns = [
    path("capture/", ReferralCaptureView.as_view(), name="referral-capture"),
    path("partner/onboard/", PartnerOnboardView.as_view(), name="partner-onboard"),
    path("partner/me/", PartnerDashboardView.as_view(), name="partner-dashboard"),
    path(
        "project/create/",
        ProjectOwnerCreateView.as_view(),
        name="project-owner-create",
    ),
    path(
        "project/<int:project_id>/",
        ProjectOwnerDetailView.as_view(),
        name="project-owner-detail",
    ),
    path(
        "project/<int:project_id>/site/create/",
        ProjectSiteOwnerCreateView.as_view(),
        name="project-site-owner-create",
    ),
    path(
        "site/bootstrap/",
        SiteOwnerBootstrapView.as_view(),
        name="site-owner-bootstrap",
    ),
    path(
        "site/create/",
        SiteOwnerCreateView.as_view(),
        name="site-owner-create",
    ),
    path(
        "site/owner-sites/",
        SiteOwnerSitesListView.as_view(),
        name="site-owner-sites-list",
    ),
    path(
        "site/integration/",
        SiteOwnerIntegrationView.as_view(),
        name="site-owner-integration",
    ),
    path(
        "site/integration/diagnostics/",
        SiteOwnerIntegrationDiagnosticsView.as_view(),
        name="site-owner-integration-diagnostics",
    ),
    path(
        "site/reachability/",
        SiteOwnerReachabilityView.as_view(),
        name="site-owner-reachability",
    ),
    path(
        "site/integration/analytics/",
        SiteOwnerIntegrationAnalyticsView.as_view(),
        name="site-owner-integration-analytics",
    ),
    path(
        "site/integration/members/",
        SiteOwnerSiteMembersListView.as_view(),
        name="site-owner-site-members",
    ),
    path(
        "site/integration/verify/",
        SiteOwnerIntegrationVerifyView.as_view(),
        name="site-owner-integration-verify",
    ),
    path(
        "site/integration/activate/",
        SiteOwnerIntegrationActivateView.as_view(),
        name="site-owner-integration-activate",
    ),
]
