from django.urls import path

from .gamification_views import (
    DailyChallengeFinishView,
    DailyChallengeLeaderboardView,
    DailyChallengeStartView,
    GamificationReferralLeaderboardView,
    GamificationShopRedeemView,
    GamificationShopSelectFrameView,
    GamificationShopView,
    GamificationSummaryView,
)
from .views import (
    PartnerDashboardView,
    PartnerOnboardView,
    PlatformServiceStatusView,
    ProjectOwnerCreateView,
    ProjectOwnerDetailView,
    ProjectSiteOwnerCreateView,
    ReferralCaptureView,
    SiteOwnerAccountActivityListView,
    SiteOwnerCreateView,
    SiteOwnerIntegrationActivateView,
    SiteOwnerBootstrapView,
    SiteOwnerIntegrationAnalyticsView,
    SiteOwnerIntegrationDiagnosticsView,
    SiteOwnerIntegrationView,
    SiteOwnerIntegrationVerifyView,
    SiteOwnerPageScanView,
    SiteOwnerReachabilityView,
    SiteOwnerSiteActivityListView,
    SiteOwnerSiteMembersListView,
    SiteOwnerSitesListView,
)

urlpatterns = [
    path(
        "gamification/summary/",
        GamificationSummaryView.as_view(),
        name="gamification-summary",
    ),
    path(
        "gamification/daily-challenge/start/",
        DailyChallengeStartView.as_view(),
        name="gamification-daily-challenge-start",
    ),
    path(
        "gamification/daily-challenge/finish/",
        DailyChallengeFinishView.as_view(),
        name="gamification-daily-challenge-finish",
    ),
    path(
        "gamification/daily-challenge/leaderboard/",
        DailyChallengeLeaderboardView.as_view(),
        name="gamification-daily-challenge-leaderboard",
    ),
    path(
        "gamification/leaderboard/",
        GamificationReferralLeaderboardView.as_view(),
        name="gamification-referral-leaderboard",
    ),
    path(
        "gamification/shop/",
        GamificationShopView.as_view(),
        name="gamification-shop",
    ),
    path(
        "gamification/shop/redeem/",
        GamificationShopRedeemView.as_view(),
        name="gamification-shop-redeem",
    ),
    path(
        "gamification/shop/select-frame/",
        GamificationShopSelectFrameView.as_view(),
        name="gamification-shop-select-frame",
    ),
    path(
        "platform-service-status/",
        PlatformServiceStatusView.as_view(),
        name="platform-service-status",
    ),
    path("capture/", ReferralCaptureView.as_view(), name="referral-capture"),
    path("partner/onboard/", PartnerOnboardView.as_view(), name="partner-onboard"),
    path("partner/me/", PartnerDashboardView.as_view(), name="partner-dashboard"),
    path(
        "project/create/",
        ProjectOwnerCreateView.as_view(),
        name="project-owner-create",
    ),
    path(
        "project/<int:project_id>/",
        ProjectOwnerDetailView.as_view(),
        name="project-owner-detail",
    ),
    path(
        "project/<int:project_id>/site/create/",
        ProjectSiteOwnerCreateView.as_view(),
        name="project-site-owner-create",
    ),
    path(
        "site/bootstrap/",
        SiteOwnerBootstrapView.as_view(),
        name="site-owner-bootstrap",
    ),
    path(
        "site/create/",
        SiteOwnerCreateView.as_view(),
        name="site-owner-create",
    ),
    path(
        "site/owner-sites/",
        SiteOwnerSitesListView.as_view(),
        name="site-owner-sites-list",
    ),
    path(
        "site/integration/",
        SiteOwnerIntegrationView.as_view(),
        name="site-owner-integration",
    ),
    path(
        "site/integration/diagnostics/",
        SiteOwnerIntegrationDiagnosticsView.as_view(),
        name="site-owner-integration-diagnostics",
    ),
    path(
        "site/reachability/",
        SiteOwnerReachabilityView.as_view(),
        name="site-owner-reachability",
    ),
    path(
        "site/page-scan/",
        SiteOwnerPageScanView.as_view(),
        name="site-owner-page-scan",
    ),
    path(
        "site/integration/analytics/",
        SiteOwnerIntegrationAnalyticsView.as_view(),
        name="site-owner-integration-analytics",
    ),
    path(
        "site/integration/members/",
        SiteOwnerSiteMembersListView.as_view(),
        name="site-owner-site-members",
    ),
    path(
        "site/integration/activity/",
        SiteOwnerSiteActivityListView.as_view(),
        name="site-owner-site-activity",
    ),
    path(
        "account/activity/",
        SiteOwnerAccountActivityListView.as_view(),
        name="site-owner-account-activity",
    ),
    path(
        "site/integration/verify/",
        SiteOwnerIntegrationVerifyView.as_view(),
        name="site-owner-integration-verify",
    ),
    path(
        "site/integration/activate/",
        SiteOwnerIntegrationActivateView.as_view(),
        name="site-owner-integration-activate",
    ),
]
