# Generated by Django 5.2.6 on 2026-04-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_data_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
