# Generated by Django 5.2.6 on 2026-04-28 01:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_slug', models.CharField(max_length=64)),
                ('target_key', models.CharField(blank=True, default='', max_length=512)),
                ('target_label', models.CharField(blank=True, default='', max_length=512)),
                ('body', models.TextField()),
                ('attachment_names', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_suppo_user_id_839e6e_idx')],
            },
        ),
    ]
