# Generated by Django 5.2.6 on 2026-04-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_supportticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='is_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
