# Generated by Django 5.2.6 on 2026-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_webauthn_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oauth_google_sub',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Google account sub'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_vk_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='VK ID user id'),
        ),
    ]
