# Generated by Django 5.2.6 on 2026-05-11 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_adminactionaudit_adminsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMfaDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('telegram', 'telegram')], max_length=16)),
                ('telegram_chat_id', models.CharField(blank=True, default='', max_length=64)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_mfa_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminMfaChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'telegram')], max_length=16)),
                ('code_hash', models.CharField(max_length=256)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_mfa_challenges', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='users.adminmfadevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='adminmfadevice',
            index=models.Index(fields=['user', 'type', 'is_active'], name='users_admin_user_id_7e82cb_idx'),
        ),
        migrations.AddIndex(
            model_name='adminmfachallenge',
            index=models.Index(fields=['user', 'channel', 'consumed_at', '-created_at'], name='users_admin_user_id_c8f325_idx'),
        ),
        migrations.AddIndex(
            model_name='adminmfachallenge',
            index=models.Index(fields=['expires_at'], name='users_admin_expires_8778e7_idx'),
        ),
    ]
