# Generated by Django 5.2.6 on 2026-05-11 21:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_adminmfadevice_adminmfachallenge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTelegramBindToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=256)),
                ('purpose', models.CharField(choices=[('initial_bind', 'initial_bind'), ('rebind', 'rebind')], max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_telegram_bind_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'consumed_at', '-created_at'], name='users_admin_user_id_5e5528_idx'), models.Index(fields=['token_hash'], name='users_admin_token_h_b33da7_idx'), models.Index(fields=['expires_at'], name='users_admin_expires_28a2c7_idx')],
            },
        ),
    ]
