# Generated by Django 5.2.6 on 2026-05-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_admintelegrambindtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminmfachallenge',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminmfachallenge',
            name='callback_nonce_hash',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='adminmfachallenge',
            name='challenge_type',
            field=models.CharField(choices=[('telegram_code', 'telegram_code'), ('telegram_approval', 'telegram_approval')], db_index=True, default='telegram_code', max_length=32),
        ),
        migrations.AddField(
            model_name='adminmfachallenge',
            name='denied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminmfachallenge',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('denied', 'denied'), ('expired', 'expired')], db_index=True, default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='adminmfachallenge',
            name='telegram_message_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='adminmfachallenge',
            name='code_hash',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='adminsession',
            name='confirmed_with',
            field=models.CharField(choices=[('development', 'development'), ('telegram', 'telegram'), ('telegram_approval', 'telegram_approval'), ('webauthn', 'webauthn'), ('totp', 'totp')], max_length=32),
        ),
    ]
